export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const USER_JOINS_ROOM = 'USER_JOINS_ROOM';
export const USER_JOIN_SUCCESS = 'USER_JOIN_SUCCESS';
export const USER_LEFT_SUCCESS = 'USER_LEFT_SUCCESS';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const UPDATE_ROOM_INFO = 'UPDATE_ROOM_INFO';
export const UPDATE_CHAT = 'UPDATE_CHAT';
